/*CREATE DATABASE*/
CREATE DATABASE ONLINE_COURSE;

/*USE THE DATABASE*/
USE ONLINE_COURSE;

/*CREATE COURSE TABLE*/
CREATE TABLE COURSE(COURSEID INT(20),
COURSENAME VARCHAR(50),
LANGUAGE VARCHAR(50),
RATINGS INT(3),
PRIMARY KEY(COURSEID),
FOREIGN KEY(USERID) REFERENCES USER(USERID));

/*CREATE USER TABLE*/
CREATE TABLE USER(USERID INT(20),
USERNAME VARCHAR(50),
PASSWORD VARCHAR(50),
TYPE VARCHAR(10),
EMAIL VARCHAR(30),
PRIMARY KEY(USERID));

/*TRAINER CREATE'S A NEW COURSE(CREATING COURSEINSTANCE TABLE)*/
CREATE TABLE COURSEINSTANCE(INSTANCEID INT(20),
COURSEID INT(20),
USERID INT(20),
STARTDATE DATE,
ENDDATE DATE,
STATUS VARCHAR(30),
PRIMARY KEY(INSTANCEID),
FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSEID));

/*USER ENROLL'S TO A COURSE(CREATING ENROLLMENT TABLE)*/
CREATE TABLE ENROLLMENT(INSTANCEID INT(20),
USERID INT(20),
FOREIGN KEY(USERID) REFERENCES USER(USERID)
FOREIGN KEY(INSTANCEID) REFERENCES COURSEINSTANCE(INSTANCEID));

/*CREATING COURSEITEM TABLE*/
CREATE TABLE COURSEITEM(COURSEID INT(20),
NAME VARCHAR(50),
DESCRIPTION VARCHAR(50),
TYPE VARCHAR(20),
CONTENT VARCHAR(50),
FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSEID));

