/*CREATE DATABASE*/
CREATE DATABASE ONLINE_COURSE;

/*USE THE DATABASE*/
USE ONLINE_COURSE;

/*CREATE USER TABLE*/
CREATE TABLE MEMBER(ID INT(20) AUTO_INCREMENT,
USERNAME VARCHAR(50),
PASSWORD VARCHAR(50),
TYPE VARCHAR(10),
EMAIL VARCHAR(30),
CREATEDON DATE,
STATUS ENUM('ACTIVE','INACTIVE'),
PRIMARY KEY(ID));

/*CREATE COURSE TABLE*/
CREATE TABLE COURSE(ID INT(20) AUTO_INCREMENT,
MEMBERID INT(20),
NAME VARCHAR(50),
LANGUAGE VARCHAR(50),
CREATEDON DATE,
STATUS ENUM('NEW','ACTIVE','TERMINATED'),
RATINGS INT(3),
PRIMARY KEY(ID),
FOREIGN KEY(MEMBERID) REFERENCES MEMBER(ID));

/*CREATING COURSEITEM TABLE*/
CREATE TABLE COURSEITEM(ID INT(20) AUTO_INCREMENT,
COURSEID INT(20),
NAME VARCHAR(50),
DESCRIPTION VARCHAR(50),
TYPE VARCHAR(20),
CONTENT VARCHAR(50),
CREATEDON DATE,
PRIMARY KEY(ID), 
FOREIGN KEY(COURSEID) REFERENCES COURSE(ID));

/*CREATING COURSEINSTANCE TABLE(TRAINER CREATE'S A NEW COURSE)*/
CREATE TABLE COURSEINSTANCE(ID INT(20) AUTO_INCREMENT,
COURSEID INT(20),
STARTDATE DATE,
ENDDATE DATE,
CREATEDON DATE,
STATUS ENUM('ACTIVE','INPROGRESS','TERMINATED'),
PRIMARY KEY(ID),
FOREIGN KEY(COURSEID) REFERENCES COURSE(ID));

/*CREATING ENROLLMENT TABLE(USER ENROLL'S TO A COURSE)*/
CREATE TABLE ENROLLMENT(ID INT(20) AUTO_INCREMENT,
INSTANCEID INT(20),
MEMBERID INT(20),
CREATEDON DATE,
PRIMARY KEY(ID),
UNIQUE (INSTANCEID, MEMBERID),
FOREIGN KEY(MEMBERID ) REFERENCES MEMBER(ID),
FOREIGN KEY(INSTANCEID) REFERENCES COURSEINSTANCE(ID));



